# Generated by Django 5.0.6 on 2024-07-16 04:38

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("social_security_number", models.CharField(max_length=11)),
                ("date_of_birth", models.DateField()),
                (
                    "image_ssn_front",
                    models.ImageField(upload_to=app.models.Client.upload_to_ssn_front),
                ),
                (
                    "image_ssn_back",
                    models.ImageField(upload_to=app.models.Client.upload_to_ssn_back),
                ),
                (
                    "image_driver_license_front",
                    models.ImageField(
                        upload_to=app.models.Client.upload_to_driver_license_front
                    ),
                ),
                (
                    "image_driver_license_back",
                    models.ImageField(
                        upload_to=app.models.Client.upload_to_driver_license_back
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("business_type", models.CharField(max_length=100)),
                ("years_in_business", models.PositiveIntegerField()),
                (
                    "annual_revenue",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_info",
                        to="app.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("expiry_date", models.CharField(max_length=5)),
                ("card_name", models.CharField(max_length=100)),
                ("cvv", models.CharField(max_length=4)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_card",
                        to="app.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_details",
                        to="app.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("purpose_of_loan", models.TextField()),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_details",
                        to="app.client",
                    ),
                ),
            ],
        ),
    ]
