# Generated by Django 5.0.6 on 2024-07-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankcard",
            name="cvv",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="businessinfo",
            name="annual_revenue",
            field=models.DecimalField(decimal_places=4, max_digits=100),
        ),
        migrations.AlterField(
            model_name="loandetails",
            name="loan_amount",
            field=models.DecimalField(decimal_places=4, max_digits=100),
        ),
    ]
