# Generated by Django 5.0.6 on 2024-07-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_bankcard_cvv_alter_businessinfo_annual_revenue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_of_birth",
            field=models.CharField(max_length=100),
        ),
    ]
