# Generated by Django 5.0.6 on 2024-07-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_client_date_of_birth"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankcard",
            old_name="card_name",
            new_name="cardholder_name",
        ),
    ]
