# Generated by Django 5.0.6 on 2024-07-17 18:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_card_name_bankcard_cardholder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="image_passport",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.Client.upload_to_passport
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="image_driver_license_back",
            field=models.ImageField(
                upload_to="",
                verbose_name=app.models.Client.upload_to_driver_license_back,
            ),
        ),
    ]
