# Generated by Django 5.0.6 on 2024-07-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_client_image_passport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankcard",
            name="card_number",
            field=models.CharField(max_length=19),
        ),
    ]
